---
title: "Progress log"
---
## To-do

* [x] Confirm the project topic
* [x] Confirm the data sources
* [x] Collect data using YouTube API
* [x] Collect data using Spotify API
* [x] Clean the data
* [x] Normalize the data
* [x] Perform Exploratory Data Analysis (EDA)
* [x] Implement regression analysis
* [x] Implement binary classification
* [x] Implement multi-class classification
* [x] Work on unsupervised learning (e.g., clustering, dimensionality reduction)
* [x] Update progress log regularly
* [x] Work on the LLM (Language Model) part of the project
* [x] Write the final report


## Member-1:Yiqin Zhou
[Click here to open](../technical-details/aboutme_yz.html)

**Weekly project contribution log:**
**T: 12-15-2024**

* [x] Completed final report section  
* [x] Completed progess- log section  
* [x] Completed unsupervised learning multi-class classification section  

**F: 12-14-2024**  

* [x] Completed EDA section  

**Th: 12-13-2024**  

* [x] Completed data collection  

**W: 12-12-2024**  

* [x] Confirmed data source in group meeting and began data collection  

**T: 12-11-2024**  

* [x] Held group meeting to decide on project topic due to changes in Spotify API permissions  

**W: 11-21-2024**  

* [x] Participated in group discussion to decide on project topic and data source  



## Member-2:Xinzhou Li

[Click here to open](../technical-details/aboutme_xinzhouli.html)

**Weekly project contribution log:**


**T: 12-15-2024**

* [x] Completed final report section  
* [x] Completed supervised classification modeling
* [x] Completed unsupervised learning classification section  

**F: 12-14-2024**  

* [x] Started supervised classification modeling 
* [x] Completed regression modeling 

**Th: 12-13-2024**  

* [x] Started data cleaning on Youtube data and did regression modeling 

**W: 12-12-2024**  

* [x] Confirmed data source in group meeting and began data collection on Youtube  

**T: 12-11-2024**  

* [x] Held group meeting to decide on project topic due to changes in Spotify API permissions  

**T: 12-09-2024**  

* [x] Did the first version of Youtube data collection

**W: 11-21-2024**  

* [x] Participated in group discussion to decide on project topic and data source